---
apiVersion: kontinue.io/v1alpha1
kind: Workload
metadata:
  name: project-name
  labels:
    app.tanzu.vmware.com/workload-type: web
spec:
  source:
    git:
      url: https://git-organization/project-name.git
